// Düzenlenebilir içerik / Editable content. Do not put secrets in this file.
window.PORTFOLIO_DATA = {
  "profile": {
    "name": "Ali Özkul",
    "github": "https://github.com/aozkul",
    "siteUrl": "https://aozkul.github.io",
    "email": null,
    "linkedin": null,
    "resumeUrl": null
  },
  "defaultLanguage": "tr",
  "projects": [
    {
      "name": "NuThings_v1",
      "mark": "N°",
      "language": "TypeScript",
      "tone": "sage",
      "url": "https://github.com/aozkul/NuThings_v1"
    },
    {
      "name": "VocabLens",
      "mark": "Aa",
      "language": "HTML",
      "tone": "lavender",
      "url": "https://github.com/aozkul/VocabLens"
    },
    {
      "name": "MathRush",
      "mark": "x²",
      "language": null,
      "tone": "peach",
      "url": "https://github.com/aozkul/MathRush"
    },
    {
      "name": "PaceQ",
      "mark": "PQ",
      "language": "HTML",
      "tone": "blue",
      "url": "https://github.com/aozkul/PaceQ"
    },
    {
      "name": "NotNow",
      "mark": "N.",
      "language": "HTML",
      "tone": "yellow",
      "url": "https://github.com/aozkul/NotNow"
    },
    {
      "name": "PayGuard",
      "mark": "PG",
      "language": null,
      "tone": "rose",
      "url": "https://github.com/aozkul/PayGuard"
    }
  ],
  "translations": {
    "tr": {
      "skip": "İçeriğe geç",
      "nav.projects": "Projeler",
      "nav.expertise": "Uzmanlık",
      "nav.about": "Hakkımda",
      "nav.github": "GitHub profilim",
      "menu.open": "Menüyü aç",
      "menu.close": "Menüyü kapat",
      "theme.dark": "Koyu temaya geç",
      "theme.light": "Açık temaya geç",
      "hero.eyebrow": "YAZILIM MÜHENDİSLİĞİ · TEKNİK LİDERLİK",
      "hero.line1": "Fikirleri,",
      "hero.line2": "çalışan yazılıma",
      "hero.line3": "dönüştürüyorum.",
      "hero.description": "Yazılım geliştirme ve teknik liderlikte 15+ yıl. Mikroservisler, veri platformları ve endüstriyel sistemler üzerinde çalışıyor; faydalı dijital ürünler geliştiriyorum.",
      "hero.cta": "Projelerimi keşfet",
      "hero.secondary": "Biraz daha yakından",
      "hero.location": "Stuttgart, Almanya",
      "hero.focus": "Sistemlerden ürünlere.",
      "board.label": "ÇALIŞMA YAKLAŞIMIM",
      "board.top": "Bir fikirden daha fazlası.",
      "board.row1.label": "ANLA",
      "board.row1.title": "Önce doğru problem.",
      "board.row1.desc": "İhtiyaçlar · Bağlam · İnsanlar",
      "board.row2.label": "TASARLA",
      "board.row2.title": "Sağlam bir temel.",
      "board.row2.desc": "Mimari · Veri · Entegrasyon",
      "board.row3.label": "GELİŞTİR",
      "board.row3.title": "Kullanılan bir ürün.",
      "board.row3.desc": "Kod · Geri bildirim · İyileştirme",
      "board.footer": "Düşünceden çalışan sisteme.",
      "strip.label": "ODAK ALANLARIM",
      "strip.one": "Backend sistemleri",
      "strip.two": "Veri platformları",
      "strip.three": "Endüstriyel yazılım",
      "strip.four": "Dijital ürünler",
      "projects.kicker": "01 / PROJELER",
      "projects.title": "Koddan bir kesit.",
      "projects.description": "GitHub profilimde yer alan seçili herkese açık depolar. Kaynak dosyaları ve proje ayrıntıları için ilgili depoyu ziyaret edebilirsiniz.",
      "projects.all": "Tüm depolar",
      "projects.filter.all": "Tümü",
      "projects.filter.label": "Projeleri dile göre filtrele",
      "projects.repository": "HERKESE AÇIK DEPO",
      "projects.link": "Depoyu incele",
      "projects.empty": "Bu filtrede proje bulunamadı.",
      "projects.count": "{count} depo gösteriliyor",
      "projects.notelabel": "Bir not",
      "projects.note": "Bu seçki herkese açık çalışmalarımı gösterir. Profesyonel deneyimimin tamamı GitHub depolarıyla sınırlı değildir.",
      "expertise.kicker": "02 / UZMANLIK",
      "expertise.title": "Sistemi bütünüyle düşünmek.",
      "expertise.description": "Yalnızca kodu değil; bileşenleri, veri akışını ve teslimata giden yolu birlikte ele alıyorum.",
      "expertise.one.title": "Backend & mimari",
      "expertise.one.text": "Mikroservisler, API tasarımı ve olay odaklı sistemler. İhtiyaca uygun, anlaşılır ve sürdürülebilir çözümler.",
      "expertise.two.title": "Veri & entegrasyon",
      "expertise.two.text": "Veri platformları ve endüstriyel sistemler arasında köprüler. Doğru veriyi, doğru akışla, doğru yere ulaştırmak.",
      "expertise.three.title": "Teknik liderlik",
      "expertise.three.text": "Gereksinimlerden teslimata: teknik kararlar, ürün sahipliği, paydaş iletişimi ve ekipler arası çalışma.",
      "expertise.one.tags": "Go / Python / .NET / API",
      "expertise.two.tags": "Kafka / RabbitMQ / SQL / Azure",
      "expertise.three.tags": "Mimari / Agile / CI/CD / Docker",
      "about.kicker": "03 / HAKKIMDA",
      "about.title": "Merakla başlayıp,\nçözümle bitirmek.",
      "about.text1": "Ben Ali Özkul. Stuttgart merkezli bir yazılım mühendisiyim. Backend geliştirme, veri altyapıları, endüstriyel yazılım ve teknik liderlik alanlarında çalışıyorum.",
      "about.text2": "Bir sistemin nasıl çalıştığı kadar, kimin hangi problemini çözdüğüyle de ilgileniyorum. Teknik tasarımı uygulamayla birleştiriyor, yeni fikirleri dijital ürünlere dönüştürmeyi seviyorum.",
      "about.years": "YILLIK DENEYİM",
      "about.work": "Yazılım geliştirme\n& teknik liderlik",
      "about.based": "STUTTGART MERKEZLİ",
      "contact.kicker": "DAHA YAKINDAN BAKIN",
      "contact.title": "Kodlar ve projeler,\nbir tık ötede.",
      "contact.description": "Herkese açık çalışmalarımı ve güncel depolarımı GitHub profilimde bulabilirsiniz.",
      "contact.github": "GitHub profilini aç",
      "contact.email": "E-posta gönder",
      "contact.linkedin": "LinkedIn",
      "contact.resume": "CV’yi aç",
      "footer.tag": "Düşün. Tasarla. Geliştir.",
      "footer.top": "Yukarı dön",
      "meta.title": "Ali Özkul — Yazılım Mühendisi & Ürün Geliştirici",
      "meta.description": "Ali Özkul’un kişisel portföyü. Stuttgart merkezli yazılım mühendisi; backend sistemleri, veri platformları, teknik liderlik ve dijital ürünler."
    },
    "en": {
      "skip": "Skip to content",
      "nav.projects": "Projects",
      "nav.expertise": "Expertise",
      "nav.about": "About",
      "nav.github": "My GitHub",
      "menu.open": "Open menu",
      "menu.close": "Close menu",
      "theme.dark": "Switch to dark theme",
      "theme.light": "Switch to light theme",
      "hero.eyebrow": "SOFTWARE ENGINEERING · TECHNICAL LEADERSHIP",
      "hero.line1": "Turning ideas",
      "hero.line2": "into software",
      "hero.line3": "that works.",
      "hero.description": "15+ years in software engineering and technical leadership. Working across microservices, data platforms and industrial systems — and building useful digital products.",
      "hero.cta": "Explore my projects",
      "hero.secondary": "A little about me",
      "hero.location": "Stuttgart, Germany",
      "hero.focus": "From systems to products.",
      "board.label": "HOW I WORK",
      "board.top": "More than an idea.",
      "board.row1.label": "UNDERSTAND",
      "board.row1.title": "The right problem first.",
      "board.row1.desc": "Needs · Context · People",
      "board.row2.label": "DESIGN",
      "board.row2.title": "A solid foundation.",
      "board.row2.desc": "Architecture · Data · Integration",
      "board.row3.label": "BUILD",
      "board.row3.title": "A product people use.",
      "board.row3.desc": "Code · Feedback · Iteration",
      "board.footer": "From thought to a working system.",
      "strip.label": "MY FOCUS",
      "strip.one": "Backend systems",
      "strip.two": "Data platforms",
      "strip.three": "Industrial software",
      "strip.four": "Digital products",
      "projects.kicker": "01 / PROJECTS",
      "projects.title": "A look at the code.",
      "projects.description": "Selected public repositories from my GitHub profile. Visit each repository to explore its source files and project details.",
      "projects.all": "All repositories",
      "projects.filter.all": "All",
      "projects.filter.label": "Filter projects by language",
      "projects.repository": "PUBLIC REPOSITORY",
      "projects.link": "Explore repository",
      "projects.empty": "No projects match this filter.",
      "projects.count": "Showing {count} repositories",
      "projects.notelabel": "A note",
      "projects.note": "This selection represents my public work. My professional experience extends beyond these GitHub repositories.",
      "expertise.kicker": "02 / EXPERTISE",
      "expertise.title": "Think in whole systems.",
      "expertise.description": "Not just the code: the components, the flow of data, and the path from requirements to delivery.",
      "expertise.one.title": "Backend & architecture",
      "expertise.one.text": "Microservices, API design and event-driven systems. Clear, maintainable solutions designed around the problem.",
      "expertise.two.title": "Data & integration",
      "expertise.two.text": "Connecting data platforms and industrial systems. Getting the right data to the right place through dependable flows.",
      "expertise.three.title": "Technical leadership",
      "expertise.three.text": "From requirements to delivery: technical decisions, product ownership, stakeholder communication and cross-team collaboration.",
      "expertise.one.tags": "Go / Python / .NET / APIs",
      "expertise.two.tags": "Kafka / RabbitMQ / SQL / Azure",
      "expertise.three.tags": "Architecture / Agile / CI/CD / Docker",
      "about.kicker": "03 / ABOUT",
      "about.title": "Start with curiosity.\nFinish with a solution.",
      "about.text1": "I’m Ali Özkul, a software engineer based in Stuttgart. My work spans backend development, data infrastructure, industrial software and technical leadership.",
      "about.text2": "I care as much about whose problem a system solves as how it works. I combine technical design with hands-on implementation, and enjoy turning new ideas into digital products.",
      "about.years": "YEARS OF EXPERIENCE",
      "about.work": "Software engineering\n& technical leadership",
      "about.based": "BASED IN STUTTGART",
      "contact.kicker": "TAKE A CLOSER LOOK",
      "contact.title": "The code is\none click away.",
      "contact.description": "Explore my public work and current repositories on my GitHub profile.",
      "contact.github": "Visit my GitHub",
      "contact.email": "Send an email",
      "contact.linkedin": "LinkedIn",
      "contact.resume": "Open résumé",
      "footer.tag": "Think. Design. Build.",
      "footer.top": "Back to top",
      "meta.title": "Ali Özkul — Software Engineer & Product Builder",
      "meta.description": "The personal portfolio of Ali Özkul. Stuttgart-based software engineer working across backend systems, data platforms, technical leadership and digital products."
    }
  }
};
