import fs from 'node:fs';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url)),out=path.join(dir,'../public/kernora');
const d=JSON.parse(fs.readFileSync(path.join(dir,'content.json'),'utf8'));
fs.mkdirSync(out,{recursive:true});fs.cpSync(path.join(dir,'assets'),path.join(out,'assets'),{recursive:true});
const cssVersion=createHash('sha256').update(fs.readFileSync(path.join(dir,'assets/site.css'))).digest('hex').slice(0,12);
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const words={
 tr:{nav:['Tanıtım','Destek','Gizlilik'],skip:'İçeriğe geç',language:'Dil',explore:'Yakından keşfet',support:'Destek al',features:'Küçük detaylar. Daha iyi bir deneyim.',how:'Başlamak kolay.',faq:'Sık sorulan sorular',help:'Bir sorunun mu var?',helpIntro:'Uygulama ve gizlilik soruların için doğrudan iletişime geç.',email:'E-posta gönder',portfolio:'Tüm projeler',source:'GitHub deposu',privacyIntro:'Verilerin nasıl işlendiğini, kullandığın hizmetleri ve seçimlerini açıkça anlatıyoruz.',supportTitle:'Birlikte çözelim.',supportIntro:'Başlamak, kullanım veya satın alma hakkında yardım mı gerekiyor? Doğru yerdesin.',start:'İlk adımlar',contact:'Doğrudan iletişim',contactText:'Cihaz modelini, iOS ve uygulama sürümünü, sorunu tekrarlama adımlarını yaz. Parola ve ödeme kartı bilgisi gönderme.',purchaseQ:'Satın alma ve erişim nasıl çalışır?',dataQ:'Verilerim nasıl işlenir?',dataA:'Uygulamaya ait veri işleme ayrıntıları ve kullandığı hizmetler gizlilik sayfasında açıklanır.',problemQ:'Bir sorunu nasıl bildirebilirim?',problemA:'Destek e-postasına cihaz ve uygulama sürümünü, beklenen sonucu ve gördüğün sorunu yaz. Ekran görüntüsü paylaşırsan özel bilgilerini önce gizle.',date:'Son güncelleme: 14 Eylül 2026',privacy:'Gizlilik politikası',terms:'Kullanım koşulları',website:'Bu web sitesi',webBody:'Bu statik sitede reklam, analitik, izleme pikseli veya iletişim formu yoktur. GitHub Pages, hizmeti sunmak ve güvenlik için IP adresi ve teknik istek bilgilerini işleyebilir. Ayrıntılar GitHub Gizlilik Bildirimi’nde yer alır.',rights:'İletişim ve seçimlerin',rightsBody:'İsteğe bağlı destek e-postaları yanıt vermek için işlenir; uygulama kayıtları otomatik eklenmez. Destek mesajındaki kişisel verilere ilişkin erişim, düzeltme veya silme taleplerini e-posta ile iletebilirsin. Mesajlar talebin çözümü ve uygulanabilir yükümlülükler için gerekli olduğu sürece tutulur.',screen:'Uygulamadan gerçek ekran görüntüsü',back:'Başa dön'},
 en:{nav:['Overview','Support','Privacy'],skip:'Skip to content',language:'Language',explore:'Take a closer look',support:'Get support',features:'Small details. A better experience.',how:'A simple way to start.',faq:'Frequently asked questions',help:'Have a question?',helpIntro:'Get in touch directly for product and privacy questions.',email:'Email support',portfolio:'All projects',source:'Source on GitHub',privacyIntro:'A clear explanation of data handling, the services involved and the choices you have.',supportTitle:'Let’s work it out.',supportIntro:'Need help getting started, using a feature or understanding access? You’re in the right place.',start:'Getting started',contact:'Direct support',contactText:'Include your device, iOS and app version, plus steps to reproduce the issue. Never send passwords or payment card information.',purchaseQ:'How do purchases and access work?',dataQ:'How is my data handled?',dataA:'The privacy policy explains this app’s data handling and the services it uses.',problemQ:'How can I report a problem?',problemA:'Email your device and app version, what you expected and what happened. Hide personal information before sharing a screenshot.',date:'Last updated: September 14, 2026',privacy:'Privacy policy',terms:'Terms of use',website:'This website',webBody:'This static site has no advertising, analytics, tracking pixels or contact forms. GitHub Pages may process IP addresses and technical request information to provide and secure hosting. See the GitHub Privacy Statement for details.',rights:'Contact and your choices',rightsBody:'Voluntary support emails are processed to answer your request; app records are not attached automatically. You can email requests to access, correct or delete personal information in support messages. Messages are kept as long as needed to resolve the request and meet applicable obligations.',screen:'Actual app screenshot',back:'Back to top'},
 de:{nav:['Überblick','Support','Datenschutz'],skip:'Zum Inhalt',language:'Sprache',explore:'Genauer ansehen',support:'Hilfe erhalten',features:'Kleine Details. Ein besseres Erlebnis.',how:'Einfach starten.',faq:'Häufige Fragen',help:'Hast du eine Frage?',helpIntro:'Direkter Kontakt für Fragen zum Produkt und Datenschutz.',email:'E-Mail senden',portfolio:'Alle Projekte',source:'Quellcode auf GitHub',privacyIntro:'Klare Informationen zur Datenverarbeitung, beteiligten Diensten und deinen Möglichkeiten.',supportTitle:'Wir helfen weiter.',supportIntro:'Fragen zum Einstieg, zu einer Funktion oder zum Zugang? Hier findest du Unterstützung.',start:'Erste Schritte',contact:'Direkter Kontakt',contactText:'Nenne Gerät, iOS- und App-Version sowie Schritte zum Nachstellen. Sende keine Passwörter oder Zahlungsdaten.',purchaseQ:'Wie funktionieren Käufe und Zugang?',dataQ:'Wie werden meine Daten verarbeitet?',dataA:'Die Datenschutzerklärung beschreibt die Datenverarbeitung dieser App und ihre verwendeten Dienste.',problemQ:'Wie melde ich ein Problem?',problemA:'Sende Gerät, App-Version, erwartetes Verhalten und das aufgetretene Problem per E-Mail. Verberge persönliche Angaben auf Screenshots.',date:'Aktualisiert am 14. September 2026',privacy:'Datenschutzerklärung',terms:'Nutzungsbedingungen',website:'Diese Website',webBody:'Diese statische Website enthält keine Werbung, Analyseskripte, Trackingpixel oder Kontaktformulare. GitHub Pages kann IP-Adressen und technische Anfragedaten für Hosting und Sicherheit verarbeiten. Einzelheiten stehen in der GitHub-Datenschutzerklärung.',rights:'Kontakt und deine Möglichkeiten',rightsBody:'Freiwillige Support-E-Mails werden zur Bearbeitung deiner Anfrage verwendet. App-Einträge werden nicht automatisch angehängt. Auskunft, Berichtigung oder Löschung personenbezogener Angaben in Supportnachrichten kannst du per E-Mail anfragen. Nachrichten werden so lange aufbewahrt, wie es zur Bearbeitung und für geltende Pflichten erforderlich ist.',screen:'Echter App-Screenshot',back:'Nach oben'}};
const langs=['tr','en','de'];const route=(lang,kind)=>`${lang==='tr'?'':lang+'/'}${kind==='home'?'':kind+'/'}index.html`;
function render(lang,kind,destination=route(lang,kind)){
 const t={...words[lang],...d.ui?.[lang]},c=d.copy[lang],folder=path.posix.dirname(destination);const rel=target=>path.posix.relative(folder,target)||'./';
 const to=(l,k)=>rel(route(l,k));const asset=f=>rel('assets/'+f)+(f==='site.css'?'?v='+cssVersion:'');const home=to(lang,'home');
 const canonical='https://aozkul.github.io/'+d.repo+'/'+route(lang,kind).replace(/index\.html$/,'');
 const nav=['home','support','privacy'].map((k,i)=>`<a href="${to(lang,k)}" ${k===kind?'aria-current="page"':''}>${t.nav[i]}</a>`).join('');
 const language=langs.map(l=>`<a lang="${l}" hreflang="${l}" href="${to(l,kind)}" ${lang===l?'aria-current="page"':''}>${l.toUpperCase()}</a>`).join('');
 const email=`mailto:ali.ozkul@icloud.com?subject=${encodeURIComponent(d.name+' Support')}`;
 const notice=c.notice?`<p class="notice">${e(c.notice)}</p>`:'';
 const contact=`<div class="contact-panel"><div><h2>${t.help}</h2><p>${t.helpIntro}</p></div><a class="button" href="${email}">${t.email}<span aria-hidden="true">↗</span></a></div>`;
 let content='';
 if(kind==='home'){
  let art='';
  if(d.repo==='kernora')art=`<div class="kernora-visual"><img class="kernora-wordmark" src="${asset('wordmark.png')}" alt="Kernora — Guiding what matters" width="1000" height="249"><p class="visual-eyebrow">${e(c.visualTitle)}</p><ol class="workflow-art">${c.visualSteps.map((v,i)=>`<li><span aria-hidden="true">0${i+1}</span><div><strong>${e(v[0])}</strong><p>${e(v[1])}</p></div></li>`).join('')}</ol><div class="visual-tools">${c.visualTools.map(v=>`<span>${e(v)}</span>`).join('')}</div>`;
  else if(d.screen){const f=d.screen.replace('{lang}',lang);art=`<div class="phone"><img fetchpriority="high" src="${asset(f)}" alt="${e(d.name+' — '+t.screen)}" width="1206" height="2622"></div><img class="floating-icon" src="${asset(d.icon)}" alt="" width="92" height="92"><span class="visual-note">${e(d.name)}<br>${e(t.screen)}</span>`;}
  else if(d.repo==='VocabLens')art=`<div class="word-art" aria-hidden="true"><div><small>DISCOVER</small>serendipity</div><div><small>ENTDECKEN</small>Wort für Wort.</div><div><small>KEŞFET</small>yeni bir kelime.</div></div>`;
  else if(d.repo==='MathRush')art='<div class="math-art" aria-hidden="true"><span>+</span><span>×</span><span>÷</span><span>=</span></div>';
  else art=`<div class="brand-art ${d.logo?'logo':''}"><img src="${asset(d.icon)}" alt="${e(d.name)}"></div>`;
  const title=c.title.split('\n').map((s,i)=>i?`<em>${e(s)}</em>`:e(s)).join('\n');
  content=`<div class="wrap"><section class="hero"><div><p class="eyebrow">${e(c.tag)}</p><h1>${title}</h1><p class="lead">${e(c.intro)}</p><div class="actions"><a class="button" href="#features">${t.explore}<span aria-hidden="true">↘</span></a><a class="button secondary" href="${to(lang,'support')}">${t.support}</a></div><p class="micro">${e(c.offer)}</p>${notice}</div><div class="visual">${art}</div></section><section class="section" id="features"><div class="section-head"><h2>${t.features}</h2></div><div class="feature-grid">${c.features.map((f,i)=>`<article class="feature"><span class="number">0${i+1} /</span><h3>${e(f[0])}</h3><p>${e(f[1])}</p></article>`).join('')}</div></section><section class="section"><h2 class="section-title">${t.how}</h2><ol class="steps">${c.steps.map(s=>`<li>${e(s)}</li>`).join('')}</ol></section><section class="last-section">${contact}</section></div>`;
 }else if(kind==='support'){
  const faq=d.faq?.[lang]??[[t.purchaseQ,c.offer],[t.dataQ,t.dataA],[t.problemQ,t.problemA]];
  content=`<div class="wrap"><header class="document-head"><p class="eyebrow">${e(d.name)} / ${t.nav[1]}</p><h1>${t.supportTitle}</h1><p class="lead">${t.supportIntro}</p></header><div class="support-grid"><article class="support-card"><span class="eyebrow">01 /</span><h2>${t.start}</h2><ol>${c.steps.map(s=>`<li>${e(s)}</li>`).join('')}</ol></article><article class="support-card"><span class="eyebrow">02 /</span><h2>${t.contact}</h2><p>${t.contactText}</p><a class="button" href="${email}">${t.email} ↗</a></article></div><section class="section" style="margin-top:56px"><h2 class="section-title">${t.faq}</h2><div class="faq">${faq.map(([q,a])=>`<details><summary>${e(q)}</summary><p>${e(a)}</p></details>`).join('')}</div>${notice}</section></div>`;
 }else{
  const sections=kind==='terms'?d.terms[lang]:d.privacy[lang];
  const all=kind==='privacy'&&!d.preservePrivacy?[...sections,[t.website,t.webBody],[t.rights,t.rightsBody]]:sections;
  const body=all.map(([h,p],i)=>`<section id="section-${i+1}"><h2>${e(h)}</h2>${d.rawPrivacy&&kind==='privacy'?p:`<p>${e(p).replaceAll('https://policies.google.com/privacy','<a href="https://policies.google.com/privacy">Google Privacy Policy</a>')}</p>`}</section>`).join('');
  content=`<div class="wrap"><header class="document-head"><p class="eyebrow">${e(d.name)} / ${kind==='privacy'?t.nav[2]:t.terms}</p><h1>${kind==='privacy'?(lang==='de'?'Datenschutz&shy;erklärung':t.privacy):t.terms}</h1><p class="lead">${kind==='terms'? (lang==='tr'?'Uygulamayı kullanırken geçerli olan koşullar.':lang==='de'?'Bedingungen für die Nutzung der App.':'The conditions for using the app.'):t.privacyIntro}</p><p class="micro">${t.date}</p></header><div class="document-layout"><nav class="toc" aria-label="${e(t.nav[2])}">${all.map(([h],i)=>`<a href="#section-${i+1}">${e(h)}</a>`).join('')}</nav><article class="policy">${body}<section><p><a href="mailto:ali.ozkul@icloud.com">ali.ozkul@icloud.com</a></p><p><a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub Privacy Statement ↗</a></p>${kind==='terms'?'':`<p><a href="${to(lang,'support')}">${t.support} →</a></p>`}</section></article></div></div>`;
 }
 const html=`<!doctype html><html lang="${lang}" style="--accent:${d.color};--secondary:${d.secondary}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(d.name)} — ${kind==='home'?e(c.title.replace('\n',' ')):kind==='support'?t.nav[1]:kind==='privacy'?t.privacy:t.terms}</title><meta name="description" content="${e(kind==='home'?c.intro:kind==='support'?t.supportIntro:t.privacyIntro)}"><meta name="theme-color" content="#090b11"><link rel="canonical" href="${canonical}">${langs.map(l=>`<link rel="alternate" hreflang="${l}" href="https://aozkul.github.io/${d.repo}/${route(l,kind).replace(/index\.html$/,'')}">`).join('')}<meta property="og:type" content="website"><meta property="og:title" content="${e(d.name+' — '+c.title.replace('\n',' '))}"><meta property="og:description" content="${e(c.intro)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="https://aozkul.github.io/${d.repo}/assets/${d.icon}"><link rel="icon" href="${asset(d.icon)}"><link rel="stylesheet" href="${asset('site.css')}"></head><body id="top"><a class="skip" href="#main">${t.skip}</a><header class="header"><div class="wrap nav"><a class="brand ${d.logo?'logo':''}" href="${home}"><img src="${asset(d.icon)}" width="40" height="40" alt=""><span>${e(d.name)}</span></a><nav class="nav-links" aria-label="${e(d.name)}">${nav}</nav><nav class="languages" aria-label="${t.language}">${language}</nav></div></header><main id="main">${content}</main><footer class="footer"><div class="wrap"><div class="footer-top"><span>© 2026 Ali Orkun Özkul · ${e(d.name)}</span><nav><a href="https://aozkul.github.io/#projects">${t.portfolio} ↗</a><a href="${to(lang,'support')}">${t.nav[1]}</a><a href="${to(lang,'privacy')}">${t.nav[2]}</a>${d.terms?`<a href="${to(lang,'terms')}">${t.terms}</a>`:''}</nav></div>${notice}</div></footer></body></html>\n`;
 const p=path.join(out,destination);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,html);
}
for(const lang of langs)for(const kind of ['home','support','privacy',...(d.terms?['terms']:[])])render(lang,kind);
for(const [alias,lang,kind] of d.aliases??[])render(lang,kind,alias);
for(const name of ['app-ads.txt','Privacy Policy'])if(fs.existsSync(path.join(dir,name)))fs.copyFileSync(path.join(dir,name),path.join(out,name));
fs.writeFileSync(path.join(out,'.nojekyll'),'');
fs.writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: https://aozkul.github.io/${d.repo}/sitemap.xml\n`);
fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${langs.flatMap(l=>['home','support','privacy'].map(k=>`<url><loc>https://aozkul.github.io/${d.repo}/${route(l,k).replace(/index\.html$/,'')}</loc></url>`)).join('')}</urlset>`);
console.log(`${d.repo}: generated all localized pages and ${d.aliases?.length??0} legacy routes.`);
